sudo: required
dist: xenial
language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install .
  - pip install -r requirements.txt
script: python setup.py test
jobs:
  include:
    - stage: deploy
      python: '3.6'
      script: ./.travis/deploy.sh
      if: type != pull_request AND (branch IN (dev, master) OR tag IS present)
      addons:
        apt:
          sources:
            - sourceline: 'deb https://download.docker.com/linux/ubuntu/ xenial stable'
              key_url: 'https://download.docker.com/linux/ubuntu/gpg'
          packages:
            - docker-ce
            - docker-ce-cli
            - containerd.io
